#!/usr/bin/env python3
import datetime
import simp
import myers


def make_simp():
    with open(myers.__file__) as fp:
        mfile, _ = fp.read().split('\ndef _parse_args(')
        mfile = mfile.replace('from __future__ import print_function\n', '')

    with open(simp.__file__) as fp:
        simp_file = fp.read()

    result = simp_file.replace('from myers import diff\n', mfile).splitlines()

    timestamp = datetime.datetime.now().isoformat()
    gen = '# generated by make_simp.py on %s' % timestamp
    result.insert(1, gen)

    with open('simp', 'w') as fp:
        for line in result:
            print(line, file=fp)


if __name__ == '__main__':
    make_simp()
